spring.application.name=vaultcore
spring.datasource.url=jdbc:postgresql://localhost:5432/vaultcore_db
spring.datasource.username=postgres
spring.datasource.password=letmein
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=auto